#!/bin/bash

# Push some commits from git to the git-temp qqueue in a given hg repository.
# Note that this nukes the git-temp qqueue, if it exists.

PATH=$PATH:$(dirname $0)
set -e

hg_repo="$1"
if [[ "$1" == "" ]]; then
  echo "Usage: $(basename $0) path-to-hg-repo [git-rev]" 1&>2
  exit 255
fi

rev="$2"
if [[ "$2" == "" ]]; then
  rev="HEAD"
fi

git_parent_rev=$(git merge-base $rev master)
hg_parent_rev=$(git-to-hg-commit $git_parent_rev $hg_repo)

pushd "$hg_repo"
  hg pull
  hg up --rev "$hg_parent_rev"
  hg qpop -a

  # Switch to the patches queue (which we assume exists) so we can delete
  # git-temp.
  hg qqueue patches

  hg qqueue --purge git-temp || true
  hg qqueue --create git-temp
popd

git format-patch -pk $git_parent_rev -o "$hg_repo/.hg/patches-git-temp"

pushd "$hg_repo"
  pushd ".hg/patches-git-temp"
    find . -name '*.patch' > series
    git-patch-to-hg-patch $(cat series)
  popd
  hg qpush -a
popd
