#!/bin/bash

if [[ "$1" == "--help" ]]; then
  echo "Usage: $0 [GIT_REV]
Invoke \$EDITOR on the files modified in the given revision.
If no revision is given, invoke \$EDITOR on the files modified in git status."
  exit 1
fi

if [[ "$1" == "" ]]; then
  $EDITOR $(git diff --name-only)
else
  if ! echo "$1" | grep -q '\.\.'; then
    revs="$1^..$1"
  else
    revs="$1"
  fi
fi

files=$(git diff --name-only $revs)
if [[ "$files" == "" ]]; then
  echo "No files modified in range $revs."
  exit 2
fi

$EDITOR $files
