#!/bin/bash

if [[ "$1" == "--help" ]]; then
  echo "Usage: $0 [GIT_REV]
Invoke \$EDITOR on the files modified in the given revision.
If no revision is given, invoke \$EDITOR on the files modified in git status."
  exit 1
fi

if [[ "$1" == "" ]]; then
  files=$(git diff --name-only)
  if [[ "$files" == "" ]]; then
    echo "No files modified in current checkout."
    echo "Did you mean to do |git edit-files REV|?"
    exit 2
  fi

  $EDITOR $files
  exit 0
fi

if ! echo "$1" | grep -q '\.\.'; then
  revs="$1^..$1"
else
  revs="$1"
fi

files=$(git diff --name-only $revs)
if [[ "$files" == "" ]]; then
  echo "No files modified in range $revs."
  exit 2
fi

$EDITOR $files
