#!/bin/bash
set -e

# Uses push-to-hg to push revision(s) to the specified hg repository, and
# then runs the hg "trychooser" command for pushing the commits to the tryserver.

THIS_DIR=$(cd `dirname "$0"`; pwd)
TRYCHOOSER="$THIS_DIR/trychooser/trychooser"
PATH="$THIS_DIR:$PATH"

hg_cmd() {
  # Don't suppress HG output since trychooser uses prompts
  hg -R "$hg_repo" $@
}

hg_repo="$1"
if [[ "$1" == "-t" || "$1" == "--tip" ]]; then
  hg_repo="$2"
fi

if [[ "$hg_repo" == "" ]]; then
  echo "Usage: $(basename "$0") [-t/--tip] path-to-hg-repo [git-revs]" 1>& 2
  exit 255
fi

PREVIOUS_QUEUE=$(hg_cmd qqueue --active)

git push-to-hg $@

hg_cmd --config "extensions.trychooser=$TRYCHOOSER" trychooser
hg_cmd -q qpop -a > /dev/null
hg_cmd qqueue "$PREVIOUS_QUEUE"
