#!/bin/bash
#
# Usage: git-push-to-try [-t|--tip] [-r REVS|--rev REVS] HG_REPO TRY_PARAMS

set -e
PATH=$(dirname $0):$PATH

function hg_cmd() {
  #echo "hg "$@"" >&2
  hg -R "$hg_repo" -q $@ > /dev/null
}

# Sigh, command-line parsing in bash is so much fun.

while true; do
  if [[ "$1" == "-t" || "$1" == "--tip" ]]; then
    tip_cmd="--tip"
    shift
    continue
  fi

  if [[ "$1" == "-r" || "$1" == "--rev" ]]; then
    revs="$2"
    shift
    shift
    continue
  fi

  break
done

hg_repo=$1
shift

git-push-to-hg $tip_cmd "$hg_repo" "$revs"

commit_msg=$(hg log -R "$hg_repo" -l1 --template '{desc}')
hg_cmd qref -sl <(echo "try: $@ $commit_msg")
echo "try: $@"

hg -R "$hg_repo" push -f ssh://hg.mozilla.org/try
echo
echo "https://tbpl.mozilla.org/?tree=Try&rev=$(hg -R "$hg_repo" log -l1 --template "{node|short}")"

hg_cmd qpop -a
